# Generated by Django 6.0.4 on 2026-04-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_club_logo_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='new_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_transfers', to='main.club'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='old_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_transfers', to='main.club'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.player'),
        ),
    ]
